base_url = "https://notes.hernan.rs/"
title = "Engineering Notes"
description = "Technical notes and articles"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

theme = "apollo"

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
toc = true
use_cdn = false
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true
mathjax = false
mathjax_dollar_inline_enable = false

menu = [
    { name = "/notes", url = "/", weight = 1 },
]

socials = [
    { name = "website", url = "https://hernan.rs", icon = "home" },
]

[extra.taxonomies]
sort_by = "page_count"
reverse = true

[extra.analytics]
enabled = true

[extra.analytics.google]
tracking_id = "G-8RR90LPNB7"
